debug: false

uitid:
  consumer:
    key: ***
    secret: ***
  base_url: http://www.uitid.be/uitid/rest/

jwt:
  iss: http://culudb-jwt-provider.dev
  nbf: 0
  exp: 3600
  keys:
    public:
      file: public.pem
auth0:
  domain:
  client_id:
  client_secret:
  redirect_uri:
